'use strict';
const app=document.querySelector('#app');
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={catalog:null,cart:new Map(),coupon:'',quote:null,affiliate:'',order:null,token:'',tab:'orders',admin:null,goaffproPreview:null};
let toastTimer;
function toast(s){const t=document.querySelector('#toast');t.textContent=s;t.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.style.display='none',5000)}
async function api(path,data,token){const opts={headers:{}};if(data!==undefined){opts.method='POST';opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(data)}if(token)opts.headers['X-Order-Token']=token;opts.headers['X-Store-Request']='1';const r=await fetch('/.netlify/functions/store-next?route='+encodeURIComponent(path.replace(/^\/api/,'')),opts);const result=await r.json();if(!r.ok)throw new Error(result.error||'Request failed');return result}
const button=(label,action,cls='')=>`<button type="button" data-action="${action}" class="${cls}">${label}</button>`;
function cartData(){return{items:Array.from(state.cart,([id,quantity])=>({id,quantity})),coupon:state.coupon,affiliate:state.affiliate}}
async function calculate(){state.quote=state.cart.size?await api('/api/quote',cartData()):null}
function totals(q){return `<div class="row"><span>Subtotal</span><span>${money(q.subtotal)}</span></div><div class="row"><span>Discount</span><span>−${money(q.discount)}</span></div><div class="row"><span>Shipping</span><span>${money(q.shipping)}</span></div><div class="row"><span>Tax (demo only)</span><span>${money(q.tax)}</span></div><div class="row total"><span>Total</span><span>${money(q.total)}</span></div>`}
async function loadStore(){state.catalog=await api('/api/catalog');const slug=decodeURIComponent(location.pathname.replace(/^\/store-next\/?/,'').replace(/\/$/,''));if(slug){const a=state.catalog.affiliates.find(a=>a.slug===slug);if(!a){app.innerHTML='<h1>Storefront unavailable</h1><a href="/store-next/">Visit the main store</a>';return}state.affiliate=slug}const saved=sessionStorage.getItem('glow_order');if(saved){try{const d=JSON.parse(saved);state.order=await api('/api/orders/'+d.id,undefined,d.token);state.token=d.token;renderOrder();return}catch{sessionStorage.removeItem('glow_order')}}renderStore()}
function renderStore(){const a=state.catalog.affiliates.find(a=>a.slug===state.affiliate);app.innerHTML=`${a?`<section class="affiliate"><div class="eyebrow">Your affiliate storefront</div><h2>${esc(a.name)}’s Glow GLP’s Store</h2><p class="muted">${esc(a.bio)}</p></section>`:''}<div class="intro"><div class="eyebrow">The research collection</div><h1>Your next order,<br>all in one place.</h1><p class="muted">Choose your materials, review your total, then submit your order. Payment and receipt upload follow your order confirmation.</p></div><div class="layout"><section><label class="search">Find a product<input id="search" type="search" placeholder="Search the sample catalog"></label><div class="grid" id="products">${state.catalog.products.map(p=>`<article class="card" data-name="${esc(p.name.toLowerCase())}">${p.image?`<img class="product-image" src="${esc(p.image)}" alt="" loading="lazy">`:""}<span class="sku">${esc(p.sku)}</span><h3>${esc(p.name)}</h3><p class="stock">${p.stock} available · demonstration inventory</p><div class="bottom"><span class="price">${money(p.price)}</span><button data-action="add" data-id="${p.id}" ${p.stock===0?'disabled':''}>${p.stock?'Add to order':'Out of stock'}</button></div></article>`).join('')}</div></section><aside class="panel cart"><h2>Your order</h2>${state.cart.size?Array.from(state.cart,([id,qty])=>{const p=state.catalog.products.find(p=>p.id===id);return `<div class="line"><strong>${esc(p.name)}</strong><div class="row"><div class="qty"><button data-action="minus" data-id="${id}" aria-label="Remove one ${esc(p.name)}">−</button><span>${qty}</span><button data-action="plus" data-id="${id}" aria-label="Add one ${esc(p.name)}">+</button></div><span>${money(p.price*qty)}</span></div></div>`}).join(''):'<p class="muted">Your cart is ready when you are.</p>'}<div class="inline"><label>Coupon code<input id="coupon" value="${esc(state.coupon)}" placeholder="Try DEMO20"></label>${button('Apply','coupon','secondary')}</div>${state.quote?totals(state.quote):''}<div class="notice">Test orders only. Tax is not configured. No payment service is connected.</div>${button('Continue to checkout','checkout','full')}<p><small>Prices imported from your repository catalog. Inventory is demonstration data.</small></p></aside></div>`}
function checkout(){if(!state.cart.size){toast('Add a product first.');return}app.innerHTML=`<div class="intro"><div class="eyebrow">Checkout · local test</div><h1>Let’s save your order.</h1><p class="muted">Use fictional customer details while testing. No confirmation email will be sent.</p></div><div class="layout"><form id="checkout" class="panel"><h2>Shipping details</h2><div class="fields">${[['name','Full name','text'],['email','Email','email'],['address','Street address','text'],['city','City','text'],['state','State','text'],['zip','ZIP code','text']].map(([k,label,type])=>`<label class="${k==='address'?'wide':''}">${label}<input name="${k}" type="${type}" required maxlength="${k==='address'?500:150}" autocomplete="off"></label>`).join('')}<label class="wide">Payment method<select name="payment_method"><option value="venmo">Venmo</option><option value="paypal">PayPal</option><option value="cashapp">Cash App</option><option value="zelle">Zelle</option></select></label></div><div class="notice">Submitting reserves stock for 24 hours. A receipt keeps your order pending manual review. This is a demo, so do not send money.</div><p id="checkout-error" class="error" role="alert"></p><div class="actions"><button type="submit">Submit test order</button>${button('Back to cart','back','secondary')}</div></form><aside class="panel"><h2>Order summary</h2>${state.quote.items.map(i=>`<div class="row"><span>${esc(i.name)} × ${i.quantity}</span><span>${money(i.amount)}</span></div>`).join('')}${totals(state.quote)}${state.affiliate?`<p class="muted">Affiliate: ${esc(state.affiliate)}</p>`:''}</aside></div>`;document.querySelector('#checkout').dataset.key=crypto.randomUUID()}
function renderOrder(){const o=state.order;const method={venmo:'Venmo',paypal:'PayPal',cashapp:'Cash App',zelle:'Zelle'}[o.payment_method];app.innerHTML=`<div class="intro"><div class="eyebrow">Order saved</div><h1>${esc(o.id)}</h1><p><span class="badge ${o.status}">${esc(o.status.replaceAll('_',' '))}</span></p><p class="muted">Your order is stored locally. Keep this browser tab’s confirmation until your test is complete.</p></div><div class="split"><section class="panel"><h2>Payment instructions</h2><div class="row"><span>Amount</span><strong class="price">${money(o.total)}</strong></div><div class="row"><span>Method</span><strong>${method}</strong></div><div class="actions">${button('Copy amount','copy-amount','secondary')}${button('Copy order number','copy-order','secondary')}${button('Refresh status','refresh-order','secondary')}</div><div class="notice">Payments are disabled in this development build. Your configured recipient can be tested in the management settings, but this screen will never open a real payment link.</div><p>Reservation ends: ${new Date(o.expires*1000).toLocaleString()}. Orders with a submitted receipt wait for staff review.</p><h3>Items</h3>${o.items.map(i=>`<div class="row"><span>${esc(i.name)} × ${i.quantity}</span><span>${money(i.amount)}</span></div>`).join('')}${totals(o)}</section><section class="panel"><h2>Attach a test receipt</h2><p class="muted">Upload a sample screenshot and reference. Uploading does not mark the order paid.</p>${['awaiting_payment','payment_submitted'].includes(o.status)?`<form id="receipt"><label>Transaction reference<input name="reference" required maxlength="100" value="${esc(o.payment_reference||'')}" placeholder="DEMO-TRANSACTION-123"></label><label>Screenshot · PNG, JPEG, or WebP, up to 3 MB<input name="screenshot" type="file" accept="image/png,image/jpeg,image/webp" required></label><button type="submit">Upload test receipt</button><p class="error" id="receipt-error" role="alert"></p></form>`:`<p>This order no longer accepts receipt uploads.</p>`}${o.has_receipt?'<p>Receipt attached. Staff can view it securely in management.</p>':''}<div class="notice">Affiliate commission: ${o.commission_status==='eligible'?'eligible after verified payment':'not eligible until payment is verified'}. GoAffPro is not connected.</div>${button('Start another test order','new-order','secondary')}</section></div>`}
async function loadAdmin(){try{state.admin=await api('/api/admin/data');renderAdmin()}catch{login()}}
function login(){app.innerHTML=`<div class="intro"><div class="eyebrow">Private management</div><h1>Your store workspace.</h1><p class="muted">Sign in with the password printed when the local server starts.</p></div><form id="login" class="panel login-panel"><label>Admin password<input name="password" type="password" autocomplete="current-password" required></label><button type="submit">Sign in</button><p id="login-error" class="error" role="alert"></p></form>`}
const field=(name,label,value='',type='text')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${type==='number'?'min="0" step="0.01"':''}></label>`;
function renderAdmin(){const d=state.admin,paid=d.orders.filter(o=>['paid','shipped'].includes(o.status)),pending=d.orders.filter(o=>['awaiting_payment','payment_submitted'].includes(o.status));app.innerHTML=`<div class="row"><div><div class="eyebrow">Glow GLP’s · management</div><h1>Store control, simplified.</h1></div>${button('Sign out','logout','secondary')}</div><div class="metrics">${[[d.orders.length,'Orders submitted'],[money(paid.reduce((n,o)=>n+o.total,0)),'Verified receipts of payment'],[money(pending.reduce((n,o)=>n+o.total,0)),'Awaiting payment or review'],[money(paid.reduce((n,o)=>n+o.commission,0)),'Eligible commission estimate']].map(([n,label])=>`<div class="panel metric"><strong>${n}</strong><small>${label}</small></div>`).join('')}</div><div class="tabs" role="group" aria-label="Management views">${['orders','products','coupons','affiliates','shipping','settings'].map(t=>`<button data-action="tab" data-tab="${t}" class="${t===state.tab?'selected':''}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div><section id="admin-content">${adminContent()}</section>`}
function adminContent(){const d=state.admin;if(state.tab==='shipping')return `<div class="panel"><h2>ShipStation preparation</h2><div class="notice">Nothing is sent to ShipStation yet. Verify an order’s payment, then review the proposed shipment data.</div>${d.orders.filter(o=>['paid','shipped'].includes(o.status)).map(o=>`<div class="row"><span>${esc(o.id)} · ${esc(o.customer.name)} · ${esc(o.shipstation_status)}</span><button data-action="shipment-preview" data-id="${o.id}">Review shipment</button></div>`).join('')||'<p>No paid orders ready yet.</p>'}<pre id="shipment-payload" class="payload"></pre></div>`;if(state.tab==='orders')return `<div class="panel tablewrap"><h2>Orders</h2>${d.orders.length?`<table><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th><th>Affiliate</th><th>Review</th></tr></thead><tbody>${d.orders.map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(o.customer.name)}</td><td>${money(o.total)}</td><td><span class="badge ${o.status}">${esc(o.status.replaceAll('_',' '))}</span></td><td>${esc(o.affiliate||'Direct')}</td><td><button data-action="order-detail" data-id="${o.id}">Open</button></td></tr>`).join('')}</tbody></table>`:'<p class="muted">No orders yet. Submit a test order in the store.</p>'}</div><div id="detail"></div>`;
if(state.tab==='products')return `<div class="split"><section class="panel"><h2>Catalog</h2><p class="muted">Stock means units available after reservations.</p>${d.products.map(p=>`<div class="line"><div class="row"><strong>${esc(p.name)}</strong><button data-action="edit-product" data-id="${p.id}" class="secondary">Edit</button></div><small>${esc(p.sku)} · ${money(p.price)} · ${p.stock} available · ${p.active?'Active':'Hidden'}</small></div>`).join('')}</section><form id="product" class="panel"><h2 id="product-title">Add a product</h2><input name="id" type="hidden">${field('name','Product name')}${field('sku','Unique SKU')}${field('price','Selling price ($)',25,'number')}${field('stock','Available units',10,'number')}<label>Visibility<select name="active"><option value="1">Active</option><option value="0">Hidden</option></select></label><button type="submit">Save product</button><p class="error" role="alert"></p></form></div>`;
if(state.tab==='coupons')return `<div class="split"><section class="panel"><h2>Coupon codes</h2>${d.coupons.map(c=>`<div class="line"><div class="row"><strong>${esc(c.code)}</strong><button data-action="edit-coupon" data-code="${esc(c.code)}" class="secondary">Edit</button></div><small>${c.kind==='percent'?c.value+'%':money(c.value)} off · ${c.used}/${c.max_uses} uses reserved or paid · ${c.active?'Active':'Disabled'}</small></div>`).join('')}</section><form id="coupon-form" class="panel"><h2>Add or update a coupon</h2>${field('code','Code')}<label>Discount type<select name="kind"><option value="percent">Percentage</option><option value="fixed">Dollar amount off</option></select></label>${field('value','Percentage or dollar amount',20,'number')}${field('minimum','Minimum product subtotal ($)',0,'number')}${field('max_uses','Maximum uses',100,'number')}${field('expiry_date','Expiration (optional)','','date')}<label>Status<select name="active"><option value="1">Active</option><option value="0">Disabled</option></select></label><button type="submit">Save coupon</button><p class="error" role="alert"></p></form></div>`;
if(state.tab==='affiliates')return `${goaffproPanel()}<div class="split"><section class="panel"><h2>Personalized storefronts</h2><div class="notice">Storefront attribution works. Sending paid orders to GoAffPro and affiliate sign-in are still being built.</div>${d.affiliates.map(a=>`<div class="line"><div class="row"><strong>${esc(a.name)}</strong><button data-action="edit-affiliate" data-slug="${esc(a.slug)}" class="secondary">Edit</button></div><p><a href="/store-next/${esc(a.slug)}" target="_blank" rel="noopener">/${esc(a.slug)}</a> · ${a.commission_bps/100}% estimate · ${a.active?'Active':'Disabled'}</p><small>${esc(a.bio)}</small></div>`).join('')}</section><form id="affiliate" class="panel"><h2>Add or update an affiliate</h2>${field('slug','Store link slug (e.g. sarah)')}${field('name','Display name')}<label>Introduction<textarea name="bio" maxlength="500"></textarea></label>${field('goaffpro_id','GoAffPro affiliate ID (from your connection preview)')}${field('commission_bps','Commission basis points (1500 = 15%)',1500,'number')}<label>Status<select name="active"><option value="1">Active</option><option value="0">Disabled</option></select></label><button type="submit">Save affiliate</button><p class="error" role="alert"></p></form></div>`;
return `<form id="settings" class="panel"><h2>Shipping and payment recipients</h2><div class="notice">These settings are saved locally. Payment links remain disabled throughout this development build.</div>${field('shipping_cents','Flat shipping ($)',d.settings.shipping_cents/100,'number')}${field('free_shipping_cents','Free shipping above discounted subtotal ($; 0 disables)',d.settings.free_shipping_cents/100,'number')}${field('venmo','Official Venmo HTTPS link',d.settings.payment_links.venmo)}${field('paypal','Official PayPal HTTPS link',d.settings.payment_links.paypal)}${field('cashapp','Official Cash App HTTPS link',d.settings.payment_links.cashapp)}${field('zelle','Zelle enrolled business email, phone, or tag',d.settings.payment_links.zelle)}<button type="submit">Save settings</button><p class="error" role="alert"></p><p class="muted">Tax service, email delivery, multi-level affiliate commissions, and production hosting are not configured.</p></form>`}
function goaffproPanel(){const g=state.admin.goaffpro||{},preview=state.goaffproPreview;return `<section class="panel"><h2>GoAffPro connection</h2><p role="status">${g.verified?'Connection verified'+(g.checked_at?' · '+new Date(g.checked_at*1000).toLocaleString():''):g.configured?'Key configured · connection not yet verified':'Waiting for your GoAffPro access token in Netlify'}</p>${button('Check GoAffPro connection','goaffpro-check','secondary')}<p class="muted">This check reads up to 100 approved affiliate profiles. Order reporting is not enabled yet.</p>${preview?`<div class="tablewrap"><table><thead><tr><th>Affiliate</th><th>GoAffPro ID</th><th>Referral code</th></tr></thead><tbody>${preview.affiliates.map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.id)}</td><td>${esc(a.ref_code)}</td></tr>`).join('')}</tbody></table></div><p>${preview.affiliates.length} approved profiles returned${preview.affiliates.length===preview.limit?' · first page only':''}. Use an ID below when creating a personalized storefront.</p>`:''}</section>`}
function detail(id){const o=state.admin.orders.find(o=>o.id===id);document.querySelector('#detail').innerHTML=`<section class="panel order"><h2>${esc(o.id)} · ${money(o.total)}</h2><p><span class="badge ${o.status}">${esc(o.status.replaceAll('_',' '))}</span></p><p>${esc(o.customer.name)} · ${esc(o.customer.email)}<br>${esc(o.customer.address)}, ${esc(o.customer.city)}, ${esc(o.customer.state)} ${esc(o.customer.zip)}</p>${o.items.map(i=>`<div class="row"><span>${esc(i.name)} × ${i.quantity}</span><span>${money(i.amount)}</span></div>`).join('')}${totals(o)}<p>Method: ${esc(o.payment_method)} · Reference: ${esc(o.payment_reference||'Not submitted')}</p><p>Affiliate: ${esc(o.affiliate||'None')} · Estimated commission: ${money(o.commission)} (${o.commission_status.replaceAll('_',' ')})</p>${o.has_receipt?`<img class="receipt" src="/.netlify/functions/store-next?route=/admin/receipt/${o.id}" alt="Customer-uploaded payment receipt"><p class="muted">Verify against the actual account transaction before marking paid.</p>`:''}<div class="actions">${['awaiting_payment','payment_submitted'].includes(o.status)?`<button data-action="paid" data-id="${o.id}">Verify payment received</button><button data-action="cancel" data-id="${o.id}" class="danger">Cancel and release stock</button>`:''}${o.status==='paid'?`<label>Tracking number<input id="tracking"></label><button data-action="shipped" data-id="${o.id}">Mark shipped</button>`:''}</div>${o.tracking?`<p>Tracking: ${esc(o.tracking)}</p>`:''}</section>`;document.querySelector('#detail').scrollIntoView({behavior:'smooth',block:'start'})}
function fill(form,values){for(const [k,v]of Object.entries(values))if(form.elements[k])form.elements[k].value=v??''}
document.addEventListener('input',e=>{if(e.target.id==='search')document.querySelectorAll('#products .card').forEach(c=>c.hidden=!c.dataset.name.includes(e.target.value.toLowerCase()))});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action;b.disabled=true;try{if(['add','plus','minus'].includes(action)){const id=Number(b.dataset.id),old=state.cart.get(id)||0,newQty=old+(action==='minus'?-1:1);const p=state.catalog.products.find(p=>p.id===id);if(newQty>p.stock){toast('No more stock available.');return}if(newQty<=0)state.cart.delete(id);else state.cart.set(id,newQty);try{await calculate()}catch(err){if(old)state.cart.set(id,old);else state.cart.delete(id);throw err}renderStore()}
else if(action==='coupon'){const previous=state.coupon;state.coupon=document.querySelector('#coupon').value.trim();try{await calculate()}catch(err){state.coupon=previous;throw err}renderStore();toast('Coupon updated.')}
else if(action==='checkout'){await calculate();checkout()}
else if(action==='back')renderStore();
else if(action==='copy-amount'||action==='copy-order'){await navigator.clipboard.writeText(action==='copy-order'?state.order.id:(state.order.total/100).toFixed(2));toast('Copied.')}
else if(action==='refresh-order'){state.order=await api('/api/orders/'+state.order.id,undefined,state.token);renderOrder()}
else if(action==='new-order'){sessionStorage.removeItem('glow_order');state.order=null;state.token='';state.cart.clear();state.quote=null;state.coupon='';state.catalog=await api('/api/catalog');renderStore()}
else if(action==='goaffpro-check'){state.goaffproPreview=null;const result=await api('/api/admin/goaffpro/check',{});state.goaffproPreview=result;await loadAdmin();toast('GoAffPro connection verified.')}
else if(action==='tab'){state.tab=b.dataset.tab;renderAdmin()}
else if(action==='logout'){await api('/api/admin/logout',{});state.goaffproPreview=null;state.admin=null;login()}
else if(action==='shipment-preview'){const result=await api('/api/admin/shipment-preview',{id:b.dataset.id});document.querySelector('#shipment-payload').textContent=JSON.stringify(result,null,2)}else if(action==='order-detail')detail(b.dataset.id);
else if(action==='edit-product'){(()=>{const p=state.admin.products.find(p=>p.id===Number(b.dataset.id));fill(document.querySelector('#product'),{...p,price:p.price/100})})();document.querySelector('#product-title').textContent='Edit product'}
else if(action==='edit-coupon'){const c=state.admin.coupons.find(c=>c.code===b.dataset.code);fill(document.querySelector('#coupon-form'),{...c,value:c.kind==='fixed'?c.value/100:c.value,minimum:c.minimum/100,expiry_date:c.expires?new Date(c.expires*1000).toISOString().slice(0,10):''})}
else if(action==='edit-affiliate')fill(document.querySelector('#affiliate'),state.admin.affiliates.find(a=>a.slug===b.dataset.slug));
else if(['paid','cancel','shipped'].includes(action)){const status=action==='cancel'?'canceled':action;if(!confirm(action==='paid'?'Have you verified this exact payment in the receiving account?':action==='cancel'?'Cancel this order and release reserved stock?':'Mark this order shipped?'))return;await api('/api/admin/status',{id:b.dataset.id,status,verified:action==='paid',tracking:document.querySelector('#tracking')?.value||''});await loadAdmin();detail(b.dataset.id);toast('Order updated.')}
}catch(err){toast(err.message)}finally{b.disabled=false}});
document.addEventListener('submit',async e=>{const f=e.target;e.preventDefault();const submit=f.querySelector('[type=submit]');submit.disabled=true;const err=f.querySelector('.error');if(err)err.textContent='';try{const values=Object.fromEntries(new FormData(f));if(f.id==='login'){await api('/api/admin/login',values);await loadAdmin()}
else if(f.id==='checkout'){const customer={...values};delete customer.payment_method;const result=await api('/api/orders',{...cartData(),customer,payment_method:values.payment_method,idempotency_key:f.dataset.key});state.order=result.order;state.token=result.token;sessionStorage.setItem('glow_order',JSON.stringify({id:result.order.id,token:result.token}));renderOrder()}
else if(f.id==='receipt'){const file=f.elements.screenshot.files[0];if(!file||file.size>3*1024*1024)throw new Error('Choose a screenshot under 3 MB.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});state.order=await api('/api/orders/'+state.order.id+'/receipt',{file:data,mime:file.type,reference:values.reference},state.token);renderOrder();toast('Receipt attached; awaiting verification.')}
else if(f.id==='product'){for(const k of ['price','stock','active'])values[k]=Number(values[k]);values.price=Math.round(values.price*100);if(values.id)values.id=Number(values.id);await api('/api/admin/product',values);await loadAdmin();toast('Product saved.')}
else if(f.id==='coupon-form'){for(const k of ['value','minimum','max_uses','active'])values[k]=Number(values[k]);values.minimum=Math.round(values.minimum*100);if(values.kind==='fixed')values.value=Math.round(values.value*100);values.expires=values.expiry_date?Math.floor(new Date(values.expiry_date+'T23:59:59').getTime()/1000):0;await api('/api/admin/coupon',values);await loadAdmin();toast('Coupon saved.')}
else if(f.id==='affiliate'){values.commission_bps=Number(values.commission_bps);values.active=Number(values.active);await api('/api/admin/affiliate',values);await loadAdmin();toast('Affiliate saved.')}
else if(f.id==='settings'){await api('/api/admin/settings',{shipping_cents:Math.round(Number(values.shipping_cents)*100),free_shipping_cents:Math.round(Number(values.free_shipping_cents)*100),payment_links:Object.fromEntries(['venmo','paypal','cashapp','zelle'].map(k=>[k,values[k]]))});await loadAdmin();toast('Settings saved.')}
}catch(error){if(err)err.textContent=error.message;else toast(error.message)}finally{submit.disabled=false}});
(/\/store-next\/admin\/?$/.test(location.pathname)?loadAdmin():loadStore()).catch(err=>{app.innerHTML=`<h1>Unable to load the store</h1><p class="error">${esc(err.message)}</p>`});
