'use strict';
const crypto=require('node:crypto'),{transaction}=require('./store-db.cjs'),emails=require('./store-email.cjs');
const now=()=>Math.floor(Date.now()/1000),fail=m=>{throw new Error(m)},fingerprint=()=>crypto.createHash('sha256').update((process.env.SHIPSTATION_API_KEY||'')+':'+(process.env.SHIPSTATION_API_SECRET||'')).digest('hex');
const configured=()=>!!process.env.SHIPSTATION_API_KEY&&!!process.env.SHIPSTATION_API_SECRET;
function status(r){return{configured:configured(),connected:configured()&&r?.fingerprint===fingerprint(),enabled:configured()&&r?.fingerprint===fingerprint()&&r?.enabled===true&&r.stores?.some(x=>x.id===r.store_id),store_id:r?.store_id||null,store_name:r?.store_name||'',checked_at:r?.checked_at||null,stores:configured()&&r?.fingerprint===fingerprint()?r.stores||[]:[]}}
async function request(route,body){
 if(!configured())fail('Save the ShipStation V1 key and secret privately in Netlify first.');
 let r;try{r=await fetch('https://ssapi.shipstation.com'+route,{method:body?'POST':'GET',headers:{Authorization:'Basic '+Buffer.from(process.env.SHIPSTATION_API_KEY+':'+process.env.SHIPSTATION_API_SECRET).toString('base64'),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),redirect:'error',signal:AbortSignal.timeout(8000)})}catch{fail('ShipStation did not return a confirmed response. Check status before retrying.');}
 if(!r.ok)throw Object.assign(new Error('ShipStation returned HTTP '+r.status+'. Check credentials, subscription and API access.'),{definite:[400,401,402,403,422].includes(r.status)});
 try{return await r.json()}catch{fail('ShipStation returned an unexpected response.')}
}
async function check(){const stores=await request('/stores?showInactive=false');if(!Array.isArray(stores))fail('ShipStation returned an unexpected store list.');return{fingerprint:fingerprint(),checked_at:now(),stores:stores.filter(x=>x.active===true&&x.marketplaceId===0&&Number.isSafeInteger(x.storeId)).map(x=>({id:x.storeId,name:String(x.storeName).slice(0,150)}))}}
const eligible=o=>o?.is_test===false&&o.status==='paid'&&!!o.paid&&!!o.receipt;
function payload(o,storeId){
 if(storeId!=null&&(!Number.isSafeInteger(storeId)||storeId<1))fail('Select a verified ShipStation manual store.');
 const sum=o.items.reduce((n,i)=>n+i.amount,0);if(sum!==o.subtotal||o.discount<0||o.discount>sum||o.total!==sum-o.discount+o.shipping+o.tax)fail('Review order totals before shipping.');
 return{orderNumber:o.id,orderKey:'glow-store-next-'+o.id,orderDate:new Date(o.created*1000).toISOString(),paymentDate:o.paid?new Date(o.paid*1000).toISOString():null,orderStatus:'awaiting_shipment',customerEmail:o.customer.email,billTo:{name:o.customer.name},shipTo:{name:o.customer.name,street1:o.customer.address,city:o.customer.city,state:o.customer.state,postalCode:o.customer.zip,country:'US'},items:[...o.items.map(i=>({lineItemKey:String(i.id),sku:i.sku,name:i.name,quantity:i.quantity,unitPrice:i.price/100})),...(o.discount?[{lineItemKey:'discount',sku:'GLOW-DISCOUNT',name:'Promo and rewards discount',quantity:1,unitPrice:-o.discount/100,adjustment:true}]:[])],amountPaid:o.total/100,taxAmount:o.tax/100,shippingAmount:o.shipping/100,paymentMethod:o.payment_method,...(storeId==null?{}:{advancedOptions:{storeId}}),internalNotes:'Glow custom store. Payment verified by staff. Review package weight and service before buying postage.'}
}
function matches(r,o,storeId){return r&&Number.isSafeInteger(r.orderId)&&r.customerEmail?.toLowerCase()===o.customer.email.toLowerCase()&&r.orderNumber===o.id&&r.orderKey==='glow-store-next-'+o.id&&r.advancedOptions?.storeId===storeId&&Math.round(r.amountPaid*100)===o.total}
async function send(id){
 const claim=await transaction(async s=>{const integration=await s.get('integrations','shipstation');if(!status(integration).enabled)return{status:'not_connected',message:'Connect and enable ShipStation in Shipping first.'};const o=await s.get('orders',id);if(!eligible(o))return{status:'blocked',message:'Only live orders with a screenshot and verified payment can be sent.'};const key='shipstation-'+id,q=await s.get('outbox',key)||{id:key,provider:'shipstation',order_id:id,attempts:0};if(q.status==='synced')return{status:'synced',remote_id:q.remote_id};if(q.lease_until>now())return{status:'sending'};if(q.account_fingerprint&&q.account_fingerprint!==fingerprint())return{status:'needs_review',message:'Credentials changed after an attempt. Check the original ShipStation account.'};q.lease=crypto.randomBytes(16).toString('hex');q.lease_until=now()+90;q.status='sending';q.attempts++;await s.put('outbox',key,q);return{o,q,key,integration}});
 if(!claim.o)return claim;const{o,q,key,integration}=claim;let outcome;
 try{
  const found=await request('/orders?orderNumber='+encodeURIComponent(o.id)+'&storeId='+integration.store_id+'&pageSize=100');if(!Array.isArray(found.orders)||found.pages>1)fail('ShipStation order lookup needs review.');
  const exact=found.orders.filter(x=>x.orderNumber===o.id);
  if(exact.length){if(exact.length!==1||!matches(exact[0],o,integration.store_id))fail('ShipStation has a conflicting order. Review it before shipping.');outcome={status:'synced',remote_id:exact[0].orderId};}
  else if(q.post_started)outcome={status:'needs_review',message:'A prior send may have arrived. No duplicate will be sent. Check ShipStation and use Check / send again to reconcile.'};
  else{
   const body=payload(o,integration.store_id);
   await transaction(async s=>{const current=await s.get('outbox',key);if(current?.lease!==q.lease)fail('Shipping attempt no longer active.');current.post_started=true;current.account_fingerprint=fingerprint();await s.put('outbox',key,current)});q.post_started=true;
   const remote=await request('/orders/createorder',body);if(!matches(remote,o,integration.store_id))fail('ShipStation did not confirm the expected order.');outcome={status:'synced',remote_id:remote.orderId};
  }
 }catch(e){if(e.definite){q.post_started=false;await transaction(async s=>{const current=await s.get('outbox',key);if(current?.lease===q.lease){current.post_started=false;await s.put('outbox',key,current)}})}outcome={status:q.post_started?'needs_review':'failed',message:e.message}}
 await transaction(async s=>{const current=await s.get('outbox',key);if(current?.lease!==q.lease)return;Object.assign(current,outcome,{account_fingerprint:fingerprint(),lease_until:0,checked_at:now(),next_attempt:now()+Math.min(3600,60*2**Math.min(current.attempts,6))});await s.put('outbox',key,current);const stored=await s.get('orders',id);if(stored){stored.shipstation_status=outcome.status;stored.shipstation_message=outcome.message||'';stored.shipstation_order_id=outcome.remote_id||stored.shipstation_order_id||null;await s.put('orders',id,stored)}});
 return outcome;
}
async function tracking(id){
 const o=await transaction(async s=>{const integration=await s.get('integrations','shipstation'),o=await s.get('orders',id);if(!status(integration).enabled||o?.status!=='paid'||!o.shipstation_order_id)return null;const q=await s.get('outbox','shipstation-'+id);if(q?.account_fingerprint!==fingerprint())return null;return o});if(!o)return{status:'blocked'};
 let data;try{const remote=await request('/orders/'+o.shipstation_order_id);if(remote.orderStatus!=='shipped')return{status:'awaiting_shipment'};if(remote.orderId!==o.shipstation_order_id||remote.orderNumber!==o.id||remote.orderKey!=='glow-store-next-'+o.id)fail('Tracking order mismatch.');data=await request('/shipments?orderId='+o.shipstation_order_id+'&pageSize=100');if(!Array.isArray(data.shipments)||data.pages>1)fail('Tracking requires manual review.');const shipments=data.shipments.filter(x=>x.orderId===o.shipstation_order_id&&x.voided===false&&x.isReturnLabel===false&&typeof x.trackingNumber==='string'&&x.trackingNumber.trim());if(shipments.length!==1)fail('Missing or multiple shipments: review tracking manually.');const shipment=shipments[0];if(shipment.trackingNumber.length>150)fail('Tracking number needs review.');let emailJob;await transaction(async s=>{const stored=await s.get('orders',id);if(stored?.status!=='paid'||stored.shipstation_order_id!==o.shipstation_order_id)return;stored.status='shipped';stored.tracking=shipment.trackingNumber;stored.shipstation_status='shipped';stored.shipstation_message='';stored.shipstation_shipment_id=shipment.shipmentId;await s.put('orders',id,stored);emailJob=await emails.queueUpdate(s,stored)});await emails.safeDispatch(emailJob);return{status:'shipped'};
 }catch(e){await transaction(async s=>{const stored=await s.get('orders',id);if(stored?.status==='paid'){stored.shipstation_message=e.message;await s.put('orders',id,stored)}});return{status:'needs_review',message:e.message}}
}
async function pending(limit=2){const batch=await transaction(async s=>{const integration=await s.get('integrations','shipstation');if(!status(integration).enabled)return[];const orders=await s.list('orders'),outbox=await s.list('outbox');return orders.filter(eligible).filter(o=>{const q=outbox.find(q=>q.id==='shipstation-'+o.id);return o.shipstation_order_id||(!q?.post_started&&(q?.next_attempt||0)<=now())}).sort((a,b)=>(a.shipstation_checked_at||0)-(b.shipstation_checked_at||0)).slice(0,limit)});await Promise.all(batch.map(async o=>{if(o.shipstation_order_id)await tracking(o.id);else await send(o.id);await transaction(async s=>{const current=await s.get('orders',o.id);if(current){current.shipstation_checked_at=now();await s.put('orders',o.id,current)}})}));return{processed:batch.length}}
module.exports={configured,status,check,payload,send,tracking,pending,eligible,fingerprint};
