'use strict';
const crypto=require('node:crypto'),{transaction}=require('./store-db.cjs');const brands=require('./brands.cjs');
const now=()=>Math.floor(Date.now()/1000),hash=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
function address(v){return typeof v==='string'&&v.length<=150&&/^[^\s<>@]+@[^\s<>@]+\.[^\s<>@]+$/.test(v)&&!/[\r\n]/.test(v)}
function configuration(){
 const from=(process.env.STORE_EMAIL_FROM||'').trim(),reply=(process.env.STORE_EMAIL_REPLY_TO||from).trim();let origin='';
 try{const u=new URL(process.env.STORE_ORIGIN);if(!u.username&&!u.password&&(u.protocol==='https:'||(process.env.STORE_LOCAL&&u.protocol==='http:')))origin=u.origin}catch{}
 return{enabled:process.env.STORE_EMAIL_ENABLED==='1',key:process.env.RESEND_API_KEY||'',from,reply,origin,ready:process.env.STORE_EMAIL_ENABLED==='1'&&!!process.env.RESEND_API_KEY&&address(from)&&address(reply)&&!!origin&&(process.env.STORE_SESSION_SECRET||'').length>=32};
}
function status(){const c=configuration();return{provider:'Resend',enabled:c.enabled,configured:c.ready,from:c.from||'support@glowglps.com',reply_to:c.reply||c.from||'support@glowglps.com',message:c.ready?'Configured. Send a connection test and check the receiving inbox. Provider acceptance is not proof of inbox delivery.':'Waiting for sender-domain verification and server email settings.'}}
function key(){return crypto.createHash('sha256').update('glow-email-v1:'+process.env.STORE_SESSION_SECRET).digest()}
function seal(value){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),iv),data=Buffer.concat([c.update(JSON.stringify(value),'utf8'),c.final()]);return{iv:iv.toString('base64'),tag:c.getAuthTag().toString('base64'),data:data.toString('base64')}}
function open(v){const c=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(v.iv,'base64'));c.setAuthTag(Buffer.from(v.tag,'base64'));return JSON.parse(Buffer.concat([c.update(Buffer.from(v.data,'base64')),c.final()]).toString())}
function template(title,paragraphs,url,label,url2,label2){const text=[title,...paragraphs,...(url?[label+': '+url]:[]),...(url2?[label2+': '+url2]:[]),'Glow Lab'].join('\n\n');return{text,html:`<!doctype html><html><body style="margin:0;background:#f6f3ec;color:#1b1b1b;font-family:Arial,sans-serif"><div style="max-width:600px;margin:24px auto;background:#fff;padding:32px;border-top:4px solid #c9a24b"><p style="letter-spacing:3px;font-size:12px">GLOW LAB</p><h1 style="font-family:Georgia,serif">${esc(title)}</h1>${paragraphs.map(p=>`<p style="line-height:1.6">${esc(p)}</p>`).join('')}${url?`<p><a href="${esc(url)}" style="display:inline-block;padding:14px 20px;background:#1b1b1b;color:white;text-decoration:none">${esc(label)}</a></p><p style="font-size:12px;overflow-wrap:anywhere">${esc(url)}</p>`:''}${url2?`<p><a href="${esc(url2)}" style="display:inline-block;padding:12px 18px;border:1px solid #1b1b1b;color:#1b1b1b;text-decoration:none">${esc(label2)}</a></p>`:''}<p style="font-size:12px;color:#666">Glow Lab · Reply to this email for help.</p></div></body></html>`}}
function rebrand(v,B){if(B.id==='glow'||v==null)return v;return String(v).split('GLOW LAB').join(B.name.toUpperCase()).split('Glow Lab').join(B.name).split('#c9a24b').join(B.accent)}
function brandOrigin(o){const B=brands.orderBrand(o);return B.id!=='glow'&&B.origin?B.origin:configuration().origin}
function viewLink(o){if(!o?.token_hash||(process.env.STORE_SESSION_SECRET||'').length<32)return null;const expires=now()+30*86400,sig=crypto.createHmac('sha256',process.env.STORE_SESSION_SECRET).update('payment-reminder:'+o.id+':'+o.token_hash+':'+expires).digest('base64url');return brandOrigin(o)+'/store-next/'+(o.affiliate||'')+'#order='+o.id+'.r_'+expires+'_'+sig}
const firstName=o=>String(o.customer?.name||'').trim().split(/\s+/)[0]||'there',itemLines=o=>(o.items||[]).map(i=>i.name+' × '+i.quantity),shipToLine=o=>{const c=o.customer||{};return 'Shipping to: '+[c.name,c.address,c.city,(c.state||'')+' '+(c.zip||'')].filter(Boolean).join(', ')};
const shipDay=d=>{const m=String(d||'').match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?new Date(Date.UTC(+m[1],+m[2]-1,+m[3])).toLocaleDateString('en-US',{timeZone:'UTC',weekday:'long',month:'long',day:'numeric'}):''};
async function enqueue(s,{id,kind,to,related_id,subject,content,expires=now()+86400,setup_hash,brand}){
 const cfg=configuration();if(!cfg.ready)return null;if(await s.get('email_outbox',id))return id;
 const B=brands.get(brand);const payload={from:`${B.name} <${brands.emailFrom(B,cfg.from)}>`,reply_to:cfg.reply,to:[to],subject:rebrand(subject,B),text:rebrand(content.text,B),html:rebrand(content.html,B)};
 await s.put('email_outbox',id,{id,kind,to,related_id,status:'pending',attempts:0,created:now(),expires,next_attempt:now(),setup_hash,brand:B.id,payload:seal(payload)});return id;
}
async function queueSetup(s,link,reset=false){const url=configuration().origin+'/store-next/account-setup#'+link.customer_id+'.'+link.token;return enqueue(s,{id:'setup-'+hash(link.token),kind:reset?'password_reset':'account_setup',to:link.email,related_id:link.customer_id,setup_hash:hash(link.token),expires:link.expires,subject:reset?'Reset your Glow Lab password':'Set up your Glow Lab account',content:template(reset?'Choose a new password.':'Your Glow Lab account is ready to set up.',[reset?'We received a request to reset your password.':'Choose your password to access your orders and rewards.','This private link expires after 24 hours and works once. Do not share it.','If you did not request this email, you can ignore it.'],url,reset?'Reset password':'Set up account')})}
async function queueOrder(s,o,token){if(o.is_test!==false)return null;const url=brandOrigin(o)+'/store-next/'+(o.affiliate||'')+'#order='+o.id+'.'+token;return enqueue(s,{id:'order-confirmation-'+o.id,kind:'checkout_recovery',brand:o.brand,to:o.customer.email,related_id:o.id,subject:'Glow Lab order received '+o.id+' · '+money(o.total),content:template('Your order has been received.',['Order: '+o.id,'Ordered: '+new Date(o.created*1000).toLocaleString('en-US',{timeZone:'America/New_York',timeZoneName:'short'}),'Total: '+money(o.total),'Your order is received. Payment has not been verified. Staff will update the status to awaiting payment after sending your invoice.','If you already paid, do not pay again. You can upload your payment screenshot using your private order link, or contact us so staff can verify the payment directly. Once we verify your payment, your order will be placed in queue.'],url,'View your order')})}
async function queueSubmitted(s,o){if(o.is_test!==false)return null;return enqueue(s,{id:'order-submitted-'+o.id,kind:'order_submitted',brand:o.brand,to:o.customer.email,related_id:o.id,subject:'Glow Lab order '+o.id+' · awaiting payment verification',content:template('Your order has been submitted.',['Order: '+o.id,'Total: '+money(o.total),'We received your order and payment screenshot. Once we verify your payment, your order will be placed in queue.','Do not send another payment. Keep your private checkout link to check your order status.'],null,null)})}
async function queueUpdate(s,o){if(o.is_test!==false)return null;
if(o.status==='paid')return enqueue(s,{id:'order-paid-'+o.id,kind:'order_paid',brand:o.brand,to:o.customer.email,related_id:o.id,subject:'Glow Lab '+o.id+' · payment received · order in queue',content:template('Payment received · your order is in queue',['Hi '+firstName(o)+',','We have received your payment, and your order is now in queue.','Payment verified: '+money(o.total)+' for order '+o.id+'.',...itemLines(o),shipToLine(o),'What happens next: the moment your shipping label is created, we will email you the tracking number. When UPS gives a delivery date, we will email you that too.',...(o.points_earned?['Rewards earned: '+o.points_earned+' points.']:[])],viewLink(o),'View your order')});
if(o.status==='shipped'){const sh=o.shipment||(o.tracking?{tracking:o.tracking}:null),ups=sh?.carrier==='ups';
 return enqueue(s,{id:'order-shipped-'+o.id,kind:'order_shipped',brand:o.brand,to:o.customer.email,related_id:o.id,subject:'Your shipping label has been created · Glow Lab '+o.id,content:template('Your shipping label has been created.',['Hi '+firstName(o)+',','Your order '+o.id+' is packed and its shipping label was created'+(sh?.ship_date?' on '+shipDay(sh.ship_date):'')+'.',...(sh?[sh.service||sh.carrier_name?'Carrier: '+(sh.service||sh.carrier_name):null,'Tracking number: '+sh.tracking].filter(Boolean):['Reply to this email and we will send your tracking details.']),shipToLine(o),...itemLines(o),ups?'Tracking updates start once UPS scans your package. We will email you the delivery date as soon as UPS has it.':(sh?.tracking_url?'Use the button below to follow your package.':'')].filter(Boolean),sh?.tracking_url||null,'Track your package',viewLink(o),'View your order')})}
if(o.status==='canceled')return enqueue(s,{id:'order-canceled-'+o.id,kind:'order_canceled',brand:o.brand,to:o.customer.email,related_id:o.id,subject:'Glow Lab '+o.id+' · canceled',content:template('Order '+o.id,['Your order has been canceled. Reserved stock and rewards points have been released.','If you already sent payment, reply to this email so staff can review it.','Order total: '+money(o.total)],null,null)});
return null}
async function queueReminder(s,o,token,id){const url=brandOrigin(o)+'/store-next/'+(o.affiliate||'')+'#order='+o.id+'.'+token;return enqueue(s,{id,kind:'payment_reminder',brand:o.brand,to:o.customer.email,related_id:o.id,subject:'Friendly payment reminder · Glow Lab '+o.id,content:template('A friendly reminder about your order.',['Hi '+o.customer.name+',','Thank you for your order! We have not yet confirmed receipt of your payment.','Order: '+o.id,'Order total: '+money(o.total),'Please use your invoice or the payment options on your order page to complete payment. Once we verify receipt, your order will be placed in queue.','If you have already paid, please do not pay again. Reply to this email with your payment details or upload your screenshot so we can locate and verify your payment.','Your private order link below expires in seven days.'],url,'View your order and payment options')})}
function publicJob(j){return{id:j.id,kind:j.kind,to:j.to,related_id:j.related_id,status:j.status,attempts:j.attempts,created:j.created,accepted_at:j.accepted_at,message:j.message||'',provider_id:j.provider_id||null}}
async function dispatch(id){
 const cfg=configuration();if(!cfg.ready)return{status:'not_configured'};
 const claimed=await transaction(async s=>{
  const j=await s.get('email_outbox',id);if(!j)return null;
  if(['accepted','expired','canceled','needs_review','rejected'].includes(j.status)||j.lease_until>now())return null;
  if(j.expires<=now()){j.status='expired';delete j.payload;await s.put('email_outbox',id,j);return null}
  if(j.first_attempt&&j.first_attempt+23*3600<=now()){j.status='needs_review';j.message='Provider retry window ended. Check Resend before sending another email.';await s.put('email_outbox',id,j);return null}
  if(j.kind==='payment_reminder'){const o=await s.get('orders',j.related_id);if(!o||o.is_test!==false||!['order_received','awaiting_payment'].includes(o.status)||o.receipt||o.paid||(o.status==='awaiting_payment'&&o.expires<=now())){j.status='canceled';j.message='Reminder canceled because the order is no longer awaiting customer payment.';delete j.payload;await s.put('email_outbox',id,j);return null}if(o.customer.email!==j.to){j.status='needs_review';j.message='Order email changed. Send a new reminder to the updated address.';await s.put('email_outbox',id,j);return null}}
  if(j.setup_hash){const a=await s.get(j.kind==='staff_setup'?'staff':'customers',j.related_id);if((j.kind==='staff_setup'&&!a?.active)||!a?.setup||a.setup.token_hash!==j.setup_hash||a.setup.expires<=now()){j.status='canceled';delete j.payload;await s.put('email_outbox',id,j);return null}}
  const fingerprint=hash(cfg.key);if(j.key_fingerprint&&j.key_fingerprint!==fingerprint){j.status='needs_review';j.message='Email credentials changed after a send attempt. Check the original Resend account.';await s.put('email_outbox',id,j);return null}
  let payload;try{payload=open(j.payload)}catch{j.status='needs_review';j.message='Email content could not be decrypted. Check the store session secret.';await s.put('email_outbox',id,j);return null}
  j.status='sending';j.first_attempt||=now();j.key_fingerprint=fingerprint;j.attempts++;j.lease_until=now()+60;j.lease=crypto.randomBytes(16).toString('hex');await s.put('email_outbox',id,j);return{job:j,payload};
 });
 if(!claimed)return{status:'unchanged'};
 let state='retry',message='Email service response is uncertain. A retry will use the same idempotency key.',providerId=null;
 try{
  const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+cfg.key,'Content-Type':'application/json','Idempotency-Key':claimed.job.send_key||id},body:JSON.stringify(claimed.payload),signal:AbortSignal.timeout(8000)});
  if(r.ok){const x=await r.json();if(typeof x.id==='string'&&x.id.length<200){state='accepted';providerId=x.id;message='Accepted by Resend. Check delivery in Resend or the recipient inbox.'}}
  else if([400,401,403,404,422].includes(r.status)){state='rejected';message='Resend rejected the message (HTTP '+r.status+'). Check API permissions, verified domain and sender settings.'}
  else if(r.status===409){state='needs_review';message='Resend idempotency conflict. Check provider logs before sending again.'}
  else message='Temporary email service error (HTTP '+r.status+'). A retry is queued.';
 }catch{}
 await transaction(async s=>{const j=await s.get('email_outbox',id);if(j?.lease!==claimed.job.lease)return;j.status=state;j.message=message;j.provider_id=providerId;j.lease_until=0;j.next_attempt=now()+Math.min(3600,60*2**Math.min(j.attempts,6));if(state==='accepted'){j.accepted_at=now();delete j.payload}await s.put('email_outbox',id,j)});
 return{status:state,message};
}
async function dispatchPending(limit=4,budgetMs=0){const started=Date.now();if(!configuration().ready)return{status:'not_configured',processed:0};const ids=await transaction(async s=>(await s.list('email_outbox')).filter(j=>['pending','retry','sending'].includes(j.status)&&(j.next_attempt||0)<=now()&&(!j.lease_until||j.lease_until<=now())).sort((a,b)=>a.created-b.created).slice(0,limit).map(j=>j.id));let done=0;for(const id of ids){if(budgetMs&&Date.now()-started>budgetMs)break;await dispatch(id);done++}return{processed:done}}
async function prepareRetry(s,j){const cfg=configuration();if(!cfg.ready)throw Object.assign(new Error('Connect email settings first.'),{status:503});const payload=open(j.payload);payload.from=`${brands.get(j.brand).name} <${brands.emailFrom(brands.get(j.brand),cfg.from)}>`;payload.reply_to=cfg.reply;j.payload=seal(payload);j.status='pending';j.retry_generation=(j.retry_generation||0)+1;j.send_key=j.id+'-retry-'+j.retry_generation;delete j.key_fingerprint;delete j.first_attempt;await s.put('email_outbox',j.id,j)}
async function safeDispatch(id){if(!id)return;try{return await dispatch(id)}catch{return{status:'retry',message:'Order/account saved. Email sending needs another attempt.'}}}
async function adminData(s){return{...status(),jobs:(await s.list('email_outbox')).sort((a,b)=>b.created-a.created).slice(0,100).map(publicJob)}}
module.exports={brandOrigin,viewLink,configuration,status,template,enqueue,queueSetup,queueOrder,queueSubmitted,queueUpdate,queueReminder,dispatch,dispatchPending,safeDispatch,prepareRetry,adminData,publicJob};

