-- Add the store records table and an inactive initial catalog.
-- Existing records are preserved. Real inventory must be entered in Management.
-- Apply to a private PostgreSQL database BEFORE configuring the Netlify function.
-- Use a restricted server-only database user. Do not expose credentials in client code.
CREATE TABLE IF NOT EXISTS glow_store_records (
  kind TEXT NOT NULL,
  key TEXT NOT NULL,
  payload TEXT NOT NULL,
  PRIMARY KEY (kind, key)
);
-- This initial design serializes short mutations with an advisory transaction lock.
-- Scale-out work should separate orders, receipts and inventory into typed tables.

INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','1','{"id":1,"name":"Lipo-C with B-12 · 10 mL","sku":"lipo-c-b12-10-ml","slug":"lipo-c-b12","size":"10 mL","price":4399,"stock":0,"active":1,"image":"/lipo-c-b12.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','2','{"id":2,"name":"Acetic Acid 0.6% · 10 mL","sku":"acetic-acid-10-ml","slug":"acetic-acid","size":"10 mL","price":799,"stock":0,"active":1,"image":"/img/acetic-acid-0-6-10ml.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','3','{"id":3,"name":"BAC Water · 10 mL","sku":"bac-water-10-ml","slug":"bac-water","size":"10 mL","price":999,"stock":0,"active":1,"image":"/img/bac-water-01b1de9b.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','4','{"id":4,"name":"BAC Water · 3 mL","sku":"bac-water-3-ml","slug":"bac-water","size":"3 mL","price":499,"stock":0,"active":1,"image":"/img/bac-water-01b1de9b.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','5','{"id":5,"name":"BAC Water · 20 mL","sku":"bac-water-20-ml","slug":"bac-water","size":"20 mL","price":1799,"stock":0,"active":1,"image":"/img/bac-water-01b1de9b.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','6','{"id":6,"name":"MOTS-C · 10 mg","sku":"mots-c-10-mg","slug":"mots-c","size":"10 mg","price":3400,"stock":0,"active":1,"image":"/img/mots-c-d561218e.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','7','{"id":7,"name":"NAD+ · 500 mg","sku":"nad-500-mg","slug":"nad","size":"500 mg","price":2500,"stock":0,"active":1,"image":"/img/nad-c5a35f62.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','8','{"id":8,"name":"GHK-Cu · 100 mg","sku":"ghk-cu-100-mg","slug":"ghk-cu","size":"100 mg","price":3799,"stock":0,"active":1,"image":"/img/ghk-cu-3f52aeb5.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','9','{"id":9,"name":"GLP-2T · 10 mg","sku":"tirz-10-10-mg","slug":"tirz-10","size":"10 mg","price":4199,"stock":0,"active":1,"image":"/img/tirz-10-e10ee2ee.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','10','{"id":10,"name":"GLP-2T · 15 mg","sku":"tirz-10-15-mg","slug":"tirz-10","size":"15 mg","price":6800,"stock":0,"active":1,"image":"/img/tirz-10-e10ee2ee.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','11','{"id":11,"name":"GLP-2T · 20 mg","sku":"tirz-10-20-mg","slug":"tirz-10","size":"20 mg","price":7800,"stock":0,"active":1,"image":"/img/tirz-10-e10ee2ee.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','12','{"id":12,"name":"GLP-2T · 30 mg","sku":"tirz-10-30-mg","slug":"tirz-10","size":"30 mg","price":9900,"stock":0,"active":1,"image":"/img/tirz-10-e10ee2ee.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','13','{"id":13,"name":"GLP-3R · 10 mg","sku":"reta-10-mg","slug":"reta","size":"10 mg","price":4499,"stock":0,"active":1,"image":"/img/reta-64bc1b77.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','14','{"id":14,"name":"GLP-3R · 20 mg","sku":"reta-20-mg","slug":"reta","size":"20 mg","price":8200,"stock":0,"active":1,"image":"/img/reta-64bc1b77.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','15','{"id":15,"name":"KPV · 10 mg","sku":"kpv-10-mg","slug":"kpv","size":"10 mg","price":3399,"stock":0,"active":1,"image":"/img/kpv-662b3b3f.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','16','{"id":16,"name":"Adamax · 5 mg","sku":"adamax-5-mg","slug":"adamax","size":"5 mg","price":4800,"stock":0,"active":1,"image":"/img/adamax-b7fe2d20.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','17','{"id":17,"name":"Adamax · 10 mg","sku":"adamax-10-mg","slug":"adamax","size":"10 mg","price":5899,"stock":0,"active":1,"image":"/img/adamax-b7fe2d20.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','18','{"id":18,"name":"Glutathione · 750 mg","sku":"glutathione-750-mg","slug":"glutathione","size":"750 mg","price":3799,"stock":0,"active":1,"image":"/img/glutathione-1b682439.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','19','{"id":19,"name":"Glutathione · 1500 mg","sku":"glutathione-1500-mg","slug":"glutathione","size":"1500 mg","price":5900,"stock":0,"active":1,"image":"/img/glutathione-1b682439.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','20','{"id":20,"name":"DSIP · 5 mg","sku":"dsip-5-mg","slug":"dsip","size":"5 mg","price":3200,"stock":0,"active":1,"image":"/img/dsip-7d332825.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','21','{"id":21,"name":"Thymosin Alpha-1 · 5 mg","sku":"thymosin-alpha-1-5-mg","slug":"thymosin-alpha-1","size":"5 mg","price":4200,"stock":0,"active":1,"image":"/img/thymosin-alpha-1-43f2896f.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','22','{"id":22,"name":"TB-500 · 10 mg","sku":"tb-500-10-mg","slug":"tb-500","size":"10 mg","price":4900,"stock":0,"active":1,"image":"/img/tb-500-74f8ca73.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','23','{"id":23,"name":"KLOW · 80 mg","sku":"klow-blend-80-mg","slug":"klow-blend","size":"80 mg","price":8699,"stock":0,"active":1,"image":"/klow-blend.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','24','{"id":24,"name":"AICAR · 50 mg","sku":"aicar-50-mg","slug":"aicar","size":"50 mg","price":5200,"stock":0,"active":1,"image":"/aicar.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','25','{"id":25,"name":"AICAR · 100 mg","sku":"aicar-100-mg","slug":"aicar","size":"100 mg","price":8200,"stock":0,"active":1,"image":"/aicar.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','26','{"id":26,"name":"5-Amino-1MQ · 50 mg","sku":"5-amino-1mq-50-mg","slug":"5-amino-1mq","size":"50 mg","price":6499,"stock":0,"active":1,"image":"/5-amino-1mq.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','27','{"id":27,"name":"5-Amino-1MQ · 5 mg","sku":"5-amino-1mq-5-mg","slug":"5-amino-1mq","size":"5 mg","price":3600,"stock":0,"active":1,"image":"/5-amino-1mq.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','28','{"id":28,"name":"GLP-31 · 10 mg","sku":"ss-31-10-mg","slug":"ss-31","size":"10 mg","price":4299,"stock":0,"active":1,"image":"/ss-31.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','29','{"id":29,"name":"PT-141 · 10 mg","sku":"pt-141-10-mg","slug":"pt-141","size":"10 mg","price":3299,"stock":0,"active":1,"image":"/pt-141.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','30','{"id":30,"name":"Selank · 10 mg","sku":"selank-10-mg","slug":"selank","size":"10 mg","price":3299,"stock":0,"active":1,"image":"/selank.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','31','{"id":31,"name":"BPC-157 · 10 mg","sku":"bpc-157-10-mg","slug":"bpc-157","size":"10 mg","price":3200,"stock":0,"active":1,"image":"/bpc-157.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','32','{"id":32,"name":"Protocol 01 · 15 mL / 0.5 oz","sku":"protocol-01-15-ml-0-5-oz","slug":"protocol-01","size":"15 mL / 0.5 oz","price":4800,"stock":0,"active":1,"image":"/img/protocol-01-9f8914e0.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','33','{"id":33,"name":"Protocol 01 · 50 mL / 1.7 oz","sku":"protocol-01-50-ml-1-7-oz","slug":"protocol-01","size":"50 mL / 1.7 oz","price":11900,"stock":0,"active":1,"image":"/img/protocol-01-9f8914e0.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','34','{"id":34,"name":"Protocol 02 · 15 mL","sku":"protocol-02-15-ml","slug":"protocol-02","size":"15 mL","price":3200,"stock":0,"active":1,"image":"/img/protocol-02-27d6fb8f.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','35','{"id":35,"name":"Glow Eyes · 0.34 fl oz / 10 mL","sku":"glow-eyes-0-34-fl-oz-10-ml","slug":"glow-eyes","size":"0.34 fl oz / 10 mL","price":3999,"stock":0,"active":1,"image":"/img/glow-eyes-89a600ef.webp","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','36','{"id":36,"name":"Glow Eyes Luxe with KPV · 0.34 fl oz / 10 mL","sku":"glow-eyes-luxe-kpv-0-34-fl-oz-10-ml","slug":"glow-eyes-luxe-kpv","size":"0.34 fl oz / 10 mL","price":6499,"stock":0,"active":1,"image":"/img/glow-eyes-luxe-kpv-b8bdab23.webp","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','37','{"id":37,"name":"Rose Recovery Mist · 60 mL","sku":"rose-recovery-mist-60-ml","slug":"rose-recovery-mist","size":"60 mL","price":1900,"stock":0,"active":1,"image":"/img/rose-recovery-mist-ce0b4d94.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','38','{"id":38,"name":"Cu-Hair 01 · 30 mL","sku":"cu-hair-01-30-ml","slug":"cu-hair-01","size":"30 mL","price":4200,"stock":0,"active":1,"image":"/img/cu-hair-01-4a56d6ea.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','39','{"id":39,"name":"Cu-Hair 02 · 30 mL","sku":"cu-hair-02-30-ml","slug":"cu-hair-02","size":"30 mL","price":5500,"stock":0,"active":1,"image":"/exec-61d8973d-63fc-4fab-b605-ee1e77d64beb.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','40','{"id":40,"name":"ARA-290 · 10 mg","sku":"ara-290-10-mg","slug":"ara-290","size":"10 mg","price":4500,"stock":0,"active":1,"image":"/ara-290-10mg.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','41','{"id":41,"name":"FOX-04 · 10 mg","sku":"fox-04-10-mg","slug":"fox-04","size":"10 mg","price":7900,"stock":0,"active":1,"image":"/FOX-04-DRI-R4-Cellular-Reset.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','42','{"id":42,"name":"Tesamorelin · 5 mg","sku":"tesamorelin-5-mg","slug":"tesamorelin","size":"5 mg","price":4900,"stock":0,"active":1,"image":"/img/tesamorelin-5mg.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','43','{"id":43,"name":"Tesamorelin · 10 mg","sku":"tesamorelin-10-mg","slug":"tesamorelin","size":"10 mg","price":6900,"stock":0,"active":1,"image":"/img/tesamorelin-5mg.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','44','{"id":44,"name":"Ipamorelin · 10 mg","sku":"ipamorelin-10-mg","slug":"ipamorelin","size":"10 mg","price":6400,"stock":0,"active":1,"image":"/img/ipamorelin-10mg.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','45','{"id":45,"name":"Epithalon · 50 mg","sku":"epithalon-50-50-mg","slug":"epithalon-50","size":"50 mg","price":9900,"stock":0,"active":1,"image":"/img/epithalon-50mg.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','46','{"id":46,"name":"Vitamin B-12 · 10 mL","sku":"vitamin-b12-10-ml","slug":"vitamin-b12","size":"10 mL","price":3299,"stock":0,"active":1,"image":"/img/vitamin-b12.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','47','{"id":47,"name":"Your Story Isn’t Over · Fridge magnet","sku":"magnet-your-story-isnt-over-fridge-magnet","slug":"magnet-your-story-isnt-over","size":"Fridge magnet","price":499,"stock":0,"active":1,"image":"/img/magnet-your-story-isnt-over.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','48','{"id":48,"name":"Pep Ho For Life · Fridge magnet","sku":"magnet-pep-ho-for-life-fridge-magnet","slug":"magnet-pep-ho-for-life","size":"Fridge magnet","price":499,"stock":0,"active":1,"image":"/img/magnet-pep-ho-for-life.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','49','{"id":49,"name":"Ready for a Glow Up? · Fridge magnet","sku":"magnet-ready-for-a-glow-up-fridge-magnet","slug":"magnet-ready-for-a-glow-up","size":"Fridge magnet","price":499,"stock":0,"active":1,"image":"/img/magnet-ready-for-a-glow-up.jpg","source":"repository catalog; inventory awaiting staff entry"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','50','{"id":50,"name":"Metabolic Reset · 10 mg","sku":"bundle-737-10-mg","price":12500,"stock":0,"active":1,"image":"/product-images/product-placeholder.svg","source":"repository catalog; inventory awaiting staff entry","bundle":"737","size":"10 mg"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','51','{"id":51,"name":"Metabolic Reset · 15 mg","sku":"bundle-737-15-mg","price":15100,"stock":0,"active":1,"image":"/product-images/product-placeholder.svg","source":"repository catalog; inventory awaiting staff entry","bundle":"737","size":"15 mg"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','52','{"id":52,"name":"Metabolic Reset · 20 mg","sku":"bundle-737-20-mg","price":16200,"stock":0,"active":1,"image":"/product-images/product-placeholder.svg","source":"repository catalog; inventory awaiting staff entry","bundle":"737","size":"20 mg"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','53','{"id":53,"name":"Metabolic Reset · 30 mg","sku":"bundle-737-30-mg","price":18300,"stock":0,"active":1,"image":"/product-images/product-placeholder.svg","source":"repository catalog; inventory awaiting staff entry","bundle":"737","size":"30 mg"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','54','{"id":54,"name":"Metabolic Reset II · 10 mg","sku":"bundle-738-10-mg","price":12800,"stock":0,"active":1,"image":"/product-images/product-placeholder.svg","source":"repository catalog; inventory awaiting staff entry","bundle":"738","size":"10 mg"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','55','{"id":55,"name":"Metabolic Reset II · 20 mg","sku":"bundle-738-20-mg","price":16500,"stock":0,"active":1,"image":"/product-images/product-placeholder.svg","source":"repository catalog; inventory awaiting staff entry","bundle":"738","size":"20 mg"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','56','{"id":56,"name":"R4 Cellular Reset · 8-vial set","sku":"bundle-751-8-vial-set","price":53000,"stock":0,"active":1,"image":"/product-images/product-placeholder.svg","source":"repository catalog; inventory awaiting staff entry","bundle":"751","size":"8-vial set"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','57','{"id":57,"name":"Epithalon 100 mg Bundle · 2-vial set","sku":"bundle-774-2-vial-set","price":16999,"stock":0,"active":1,"image":"/product-images/product-placeholder.svg","source":"repository catalog; inventory awaiting staff entry","bundle":"774","size":"2-vial set"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('products','58','{"id":58,"name":"Radiance Reset Duo · 2-vial set","sku":"bundle-795-2-vial-set","price":7900,"stock":0,"active":1,"image":"/product-images/product-placeholder.svg","source":"repository catalog; inventory awaiting staff entry","bundle":"795","size":"2-vial set"}') ON CONFLICT(kind,key) DO NOTHING;
INSERT INTO glow_store_records(kind,key,payload) VALUES ('settings','main','{"shipping_cents":1500,"free_shipping_cents":25000,"demo":true,"tax_note":"Tax is not configured. This is a test order.","payment_links":{"venmo":"","paypal":"","cashapp":"","zelle":""}}') ON CONFLICT(kind,key) DO NOTHING;
