#!/usr/bin/env node
/* BUILD STEP — bakes catalog.json into index.html.
 *
 * Runs on every Netlify deploy (netlify.toml `command`). It is the ONLY thing allowed to write a price
 * into the storefront, and it writes exactly what netlify/functions/lib/pricing.js will charge. That is
 * the whole point: before this existed, the sale price was painted onto the page by a separate script
 * and the cart still totalled the regular price, so buyers were shown one number and billed another.
 *
 * It is idempotent (a pure function of catalog.json) and it FAILS THE BUILD rather than deploying a
 * storefront it could not price — a silent no-op here is an overcharge in production.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const require = createRequire(import.meta.url);
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const { priceCatalog, priceLadder } = require(join(ROOT, 'netlify/functions/lib/pricing.js'));

const die = (m) => { console.error('\n  sync-catalog FAILED: ' + m + '\n'); process.exit(1); };

const cat = JSON.parse(readFileSync(join(ROOT, 'catalog.json'), 'utf8'));
const { price, bundles } = priceCatalog(cat);
const ladder = priceLadder(cat);
let html = readFileSync(join(ROOT, 'index.html'), 'utf8');

/* ── 1. the pricing block the storefront renders from ─────────────────────────────────────────── */
const payload = {
  updated: cat.updated || '',
  shipping: { flat: Number(cat.shipping?.flat ?? 15), free_over: Number(cat.shipping?.free_over ?? 250) },
  sale: { label: cat.sale?.label || 'Sale', ends: cat.sale?.ends || null },
  price,
  coupons_hint: (cat.coupons || []).some((c) => c.active) ? 1 : 0,   // whether to show the code box at all
};

const BLOCK =
`/*GLP-PRICING-START — generated by tools/sync-catalog.mjs from catalog.json. DO NOT EDIT BY HAND. */
var GLP_PRICING = ${JSON.stringify(payload)};
(function(){                                   // one pass, before anything renders
  var M = GLP_PRICING.price || {};
  for (var i=0;i<PRODUCTS.length;i++){
    var p = PRODUCTS[i], m = M[p.slug];
    if (!m) continue;
    if (m.now != null) p.price = m.now;
    p.was = (m.was != null) ? m.was : null;
    if (m.badge) p.badge = m.badge;
    if (p.sizes && m.sizes){
      for (var j=0;j<p.sizes.length && j<m.sizes.length;j++){
        p.sizes[j].p = m.sizes[j].now;
        p.sizes[j].w = (m.sizes[j].was != null) ? m.sizes[j].was : null;
      }
    }
  }
})();
/*GLP-PRICING-END*/`;

/* Every product the storefront can put in a cart MUST be priced here, or the server would drop the
 * line at checkout and quietly undercharge. Fail the build instead. */
const slugs = [...html.matchAll(/"slug":"([a-z0-9\-]+)"/g)].map((m) => m[1]);
const missing = [...new Set(slugs)].filter((sl) => !(sl in (cat.products || {})));
if (missing.length) die('these products are in the storefront but have no price in catalog.json: ' + missing.join(', '));

const MARK = /\/\*GLP-PRICING-START[\s\S]*?\/\*GLP-PRICING-END\*\//;
if (MARK.test(html)) {
  html = html.replace(MARK, BLOCK);
} else {
  const anchor = 'let CART = {};';
  if (!html.includes(anchor)) die('anchor "' + anchor + '" not found in index.html');
  html = html.replace(anchor, anchor + '\n' + BLOCK);
}

/* ── 2. the bundle table: [label, price charged, price struck through] ────────────────────────── */
const B = Object.keys(cat.bundles || {}).map((wc) => {
  const b = cat.bundles[wc];
  const rows = bundles[wc] || [];
  return { img: b.img, name: b.name, sub: b.sub, wc: b.wc ?? Number(wc),
           sizes: rows.map((z) => [z.s, z.now, z.was]) };
});
const bRe = /var B=\[[\s\S]*?\];\n/;
if (!bRe.test(html)) die('bundle table "var B=[...]" not found in index.html');
html = html.replace(bRe, 'var B=' + JSON.stringify(B) + ';\n');

/* ── 3. refuse to ship a storefront that still paints prices it will not charge ───────────────── */
for (const ghost of ['glp-sale-aug2026', 'glp-sale-nad']) {
  if (html.includes('id="' + ghost + '"')) die('display-only sale script <' + ghost + '> is back — it shows prices the cart does not charge');
}
if (/\*\s*0\.8\b/.test(html.slice(html.indexOf('id="glp-bundles-js"'), html.indexOf('id="glp-bundles-js"') + 5000))) {
  die('a hardcoded *0.8 bundle discount is back in the bundle renderer — bundle prices must come from catalog.json');
}

writeFileSync(join(ROOT, 'index.html'), html);

const onSale = Object.values(price).filter((r) => r.was != null).length;
console.log('sync-catalog: %d products (%d on sale), %d bundles, %d live price points, %d active coupon(s)',
  Object.keys(price).length, onSale, B.length, ladder.length, (cat.coupons || []).filter((c) => c.active).length);
console.log('sync-catalog: ladder ' + ladder[0].toFixed(2) + ' … ' + ladder[ladder.length - 1].toFixed(2));
