'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'glow-email-'));Object.assign(process.env,{STORE_LOCAL:'1',STORE_SQLITE_PATH:path.join(tmp,'store.sqlite'),STORE_ADMIN_PASSWORD:'email-test-admin-password',STORE_SESSION_SECRET:'email-test-session-secret-long-enough',STORE_ORIGIN:'http://127.0.0.1:8787'});
const {transaction}=require('../../netlify/functions/lib/store-db.cjs'),{seed}=require('../../tools/store/seed-data.cjs'),{handle}=require('../../netlify/functions/lib/store-core.cjs'),emails=require('../../netlify/functions/lib/store-email.cjs'),accounts=require('../../netlify/functions/lib/customer-accounts.cjs');let cookie,liveOrder,setupCustomer;const originalFetch=global.fetch;
const call=(p,b,h={})=>handle({path:p,method:b===undefined?'GET':'POST',headers:{'x-store-request':'1',...h},body:b||{}}),admin=(p,b)=>call(p,b,{cookie});
function orderBody(extra={}){return{items:[{id:1,quantity:1}],payment_method:'zelle',idempotency_key:crypto.randomUUID(),customer:{name:'Email Test',email:'orders@example.com',phone:'2025550101',address:'1 Test St',city:'Test',state:'GA',zip:'30301'},...extra}}
function ready(){Object.assign(process.env,{RESEND_API_KEY:'fixture-private-resend-key',STORE_EMAIL_FROM:'support@example.com',STORE_EMAIL_REPLY_TO:'help@example.com',STORE_EMAIL_ENABLED:'1'})}
before(async()=>{await transaction(seed);cookie=(await call('/admin/login',{password:process.env.STORE_ADMIN_PASSWORD})).headers['Set-Cookie'].split(';')[0];await transaction(async s=>{const x=await s.get('settings','main');await s.put('settings','main',{...x,demo:false,checkout_enabled:true,tax_mode:'none',payment_links:{zelle:'recipient@example.com'}})})});after(()=>{global.fetch=originalFetch;fs.rmSync(tmp,{recursive:true,force:true})});
test('no credentials sends nothing and changing enabled flag is explicit',async()=>{let sent=0;global.fetch=async()=>{sent++;throw Error('Unexpected send')};delete process.env.RESEND_API_KEY;assert.equal(emails.status().configured,false);await call('/orders',orderBody());assert.equal(sent,0);ready();process.env.STORE_EMAIL_ENABLED='0';await call('/orders',orderBody());assert.equal(sent,0);process.env.STORE_EMAIL_ENABLED='1';assert.equal((await call('/catalog')).body.settings.email_enabled,true)});
test('email failure preserves order and stock; private confirmation payload is encrypted and retry uses the same request',async()=>{let payload,key;global.fetch=async(url,opts)=>{assert.equal(url,'https://api.resend.com/emails');assert.equal(opts.headers.Authorization,'Bearer fixture-private-resend-key');payload=JSON.parse(opts.body);key=opts.headers['Idempotency-Key'];throw Error('private service failure')};const stock=(await call('/catalog')).body.products[0].stock;liveOrder=(await call('/orders',orderBody())).body;assert.equal(liveOrder.order.status,'order_received');assert.equal(liveOrder.email.status,'retry');assert.equal((await call('/catalog')).body.products[0].stock,stock-1);assert.ok(payload.text.includes('#order='+liveOrder.order.id+'.'+liveOrder.token));assert.equal(payload.to[0],'orders@example.com');assert.equal(payload.from,'Glow Lab <support@example.com>');assert.equal(payload.reply_to,'help@example.com');assert.match(payload.text,/awaiting payment/);const stored=await transaction(s=>s.get('email_outbox',key));assert.equal(JSON.stringify(stored).includes(liveOrder.token),false);assert.equal(JSON.stringify((await admin('/admin/email')).body).includes(liveOrder.token),false);assert.equal(JSON.stringify((await call('/catalog')).body).includes('fixture-private-resend-key'),false);});
test('concurrent sends and accepted retries cannot duplicate an email',async()=>{const id='order-confirmation-'+liveOrder.order.id;let sent=0;global.fetch=async(url,opts)=>{sent++;assert.equal(opts.headers['Idempotency-Key'],id);await new Promise(r=>setTimeout(r,5));return{ok:true,status:200,json:async()=>({id:'provider-confirmed'})}};const r=await Promise.all([emails.dispatch(id),emails.dispatch(id)]);assert.equal(sent,1);assert.ok(r.some(x=>x.status==='accepted'));await emails.dispatch(id);assert.equal(sent,1);const j=await transaction(s=>s.get('email_outbox',id));assert.equal(j.status,'accepted');assert.equal(j.payload,undefined);});
test('ambiguous sends beyond provider window and changed credentials require review',async()=>{global.fetch=async()=>{throw Error('timeout')};async function queued(id){await transaction(s=>emails.enqueue(s,{id,kind:'connection_test',to:'test@example.com',subject:'Test',content:emails.template('Test',[],null,null),expires:Math.floor(Date.now()/1000)+172800}));await emails.dispatch(id)}await queued('old-uncertain');await transaction(async s=>{const j=await s.get('email_outbox','old-uncertain');j.first_attempt-=86400;await s.put('email_outbox',j.id,j)});let sent=0;global.fetch=async()=>{sent++;return{ok:true,json:async()=>({id:'unexpected'})}};await emails.dispatch('old-uncertain');assert.equal(sent,0);assert.equal((await transaction(s=>s.get('email_outbox','old-uncertain'))).status,'needs_review');global.fetch=async()=>{throw Error('timeout')};await queued('changed-key');process.env.RESEND_API_KEY='different-fixture-key';global.fetch=async()=>{sent++;return{ok:true,json:async()=>({id:'unexpected'})}};await emails.dispatch('changed-key');assert.equal(sent,0);assert.equal((await transaction(s=>s.get('email_outbox','changed-key'))).status,'needs_review');ready()});
test('signup sends private single-use setup to its canonical address; existing verified and held records stay private',async()=>{const sent=[];global.fetch=async(url,opts)=>{sent.push(JSON.parse(opts.body));return{ok:true,status:200,json:async()=>({id:'setup-'+sent.length})}};const first=await call('/account/register',{name:'Customer',email:'AUTO@example.com'}),second=await call('/account/register',{name:'Other Name',email:'auto@example.com'});assert.deepEqual(first.body,second.body);assert.equal(sent.length,1);assert.equal(sent[0].to[0],'auto@example.com');assert.equal(first.body.token,undefined);const match=sent[0].text.match(/#([a-f0-9]{64})\.([A-Za-z0-9_-]{43})/);assert.ok(match);setupCustomer={id:match[1],email:'auto@example.com'};const j=await transaction(s=>s.get('email_outbox','setup-'+accounts.hash(match[2])));assert.equal(JSON.stringify(j).includes(match[2]),false);const setup=await call('/account/setup',{customer_id:match[1],token:match[2],password:'an email customer secure passphrase'});setupCustomer.cookie=setup.headers['Set-Cookie'].split(';')[0];await assert.rejects(call('/account/setup',{customer_id:match[1],token:match[2],password:'an email customer secure passphrase'}),e=>e.status===403);await call('/account/register',{name:'Someone',email:'auto@example.com'});assert.equal(sent.length,1);await call('/account/register',{name:'Held',email:'typo@gmail.coml'});assert.equal(sent.length,1)});
test('password reset has a generic response and stale/expired setup emails are suppressed',async()=>{let sent=0;global.fetch=async()=>{sent++;return{ok:true,status:200,json:async()=>({id:'reset-sent'})}};await transaction(async s=>{const a=await s.get('customers',setupCustomer.id);a.last_setup_email=0;await s.put('customers',a.id,a)});const known=await call('/account/forgot-password',{email:setupCustomer.email}),unknown=await call('/account/forgot-password',{email:'missing@example.com'});assert.deepEqual(known.body,unknown.body);assert.equal(sent,1);assert.equal((await call('/account',undefined,{cookie:setupCustomer.cookie})).body.customer.verified,true);const link=await transaction(async s=>{const r=await accounts.issueSetup(s,setupCustomer.id);await emails.queueSetup(s,r);return r});await transaction(s=>accounts.issueSetup(s,setupCustomer.id));await emails.dispatch('setup-'+accounts.hash(link.token));assert.equal(sent,1);assert.equal((await transaction(s=>s.get('email_outbox','setup-'+accounts.hash(link.token)))).status,'canceled');});
test('payment and shipment updates are queued once; preview orders send nothing',async()=>{await assert.rejects(admin('/admin/status',{id:liveOrder.order.id,status:'paid'}),/Confirm/);const subjects=[],messages=[];global.fetch=async(url,opts)=>{subjects.push(JSON.parse(opts.body).subject);messages.push(JSON.parse(opts.body).text);return{ok:true,status:200,json:async()=>({id:'update-'+subjects.length})}};await admin('/admin/status',{id:liveOrder.order.id,status:'paid',verified:true});await admin('/admin/status',{id:liveOrder.order.id,status:'shipped',tracking:'TRACK123'});assert.equal(subjects.length,2);assert.match(subjects[0],/payment received/);assert.match(messages[0],/We have received your payment, and your order is now in queue/);assert.match(subjects[1],/shipped/);await transaction(async s=>{const settings=await s.get('settings','main');await s.put('settings','main',{...settings,demo:true})});const preview=(await call('/orders',orderBody())).body.order;await admin('/admin/status',{id:preview.id,status:'paid',verified:true});assert.equal(subjects.length,2)});
test('admin email controls are private; test replay cannot send twice; definite rejection can retry corrected sender',async()=>{await assert.rejects(call('/admin/email'),e=>e.status===401);await assert.rejects(call('/admin/email/test',{email:'test@example.com',idempotency_key:'test'}),e=>e.status===401);let sent=0;global.fetch=async()=>{sent++;return{ok:true,status:200,json:async()=>({id:'connection'})}};const test={email:'owner@example.com',idempotency_key:'test-once'};await admin('/admin/email/test',test);await admin('/admin/email/test',test);assert.equal(sent,1);const id='rejected-fixture';await transaction(s=>emails.enqueue(s,{id,kind:'connection_test',to:'owner@example.com',subject:'Test',content:emails.template('Test',[],null,null)}));global.fetch=async()=>({ok:false,status:403});assert.equal((await emails.dispatch(id)).status,'rejected');process.env.STORE_EMAIL_FROM='corrected@example.com';global.fetch=async(url,opts)=>{assert.equal(JSON.parse(opts.body).from,'Glow Lab <corrected@example.com>');assert.equal(opts.headers['Idempotency-Key'],id+'-retry-1');return{ok:true,status:200,json:async()=>({id:'corrected'})}};assert.equal((await admin('/admin/email/retry',{id})).body.status,'accepted')});
test('scheduled processing honors backoff and limits each run',async()=>{let sent=0;global.fetch=async()=>{sent++;return{ok:true,status:200,json:async()=>({id:'worker-'+sent})}};await transaction(async s=>{for(const id of ['worker-due','worker-later'])await emails.enqueue(s,{id,kind:'connection_test',to:'owner@example.com',subject:'Test',content:emails.template('Test',[],null,null)});const later=await s.get('email_outbox','worker-later');later.next_attempt=Math.floor(Date.now()/1000)+600;await s.put('email_outbox',later.id,later)});assert.equal((await emails.dispatchPending(1)).processed,1);assert.equal(sent,1);assert.equal((await emails.dispatchPending(1)).processed,0);assert.equal(sent,1)});

test('draft recovery and final screenshot confirmation are distinct; retries send final email only once',async()=>{
 await transaction(async s=>{const settings=await s.get('settings','main');await s.put('settings','main',{...settings,demo:false})});
 const payloads=[];global.fetch=async(url,opts)=>{payloads.push(JSON.parse(opts.body));return{ok:true,status:200,json:async()=>({id:'flow-'+payloads.length})}};
 const r=(await call('/orders',orderBody())).body;assert.match(payloads[0].text,/order has been received/);assert.match(payloads[0].text,/Payment has not been verified/);
 const raw=await require('sharp')({create:{width:20,height:20,channels:3,background:'#fff'}}).png().toBuffer(),body={mime:'image/png',file:raw.toString('base64')},h={'x-order-token':r.token};
 await call('/orders/'+r.order.id+'/receipt',body,h);assert.match(payloads[1].text,/order has been submitted/);assert.match(payloads[1].text,/Once we verify your payment, your order will be placed in queue/);
 await call('/orders/'+r.order.id+'/receipt',body,h);assert.equal(payloads.length,2);
});

