'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'glow-shipping-'));Object.assign(process.env,{STORE_LOCAL:'1',STORE_SQLITE_PATH:path.join(dir,'store.sqlite'),SHIPSTATION_API_KEY:'fixture-key',SHIPSTATION_API_SECRET:'fixture-secret'});
const {transaction}=require('../../netlify/functions/lib/store-db.cjs'),shipping=require('../../netlify/functions/lib/shipstation.cjs');const originalFetch=global.fetch;
let n=0;async function fixture(extra={}){const o={id:'GLP-TEST'+(++n),created:1700000000,paid:1700001000,status:'paid',is_test:false,receipt:'fixture-private-image',customer:{name:'Fixture',email:'fixture@example.com',address:'1 Example Street',city:'Example',state:'GA',zip:'30301'},items:[{id:1,sku:'FIXTURE',name:'Fixture item',price:3399,quantity:1,amount:3399}],subtotal:3399,discount:339,shipping:1500,tax:0,total:4560,payment_method:'zelle',...extra};await transaction(s=>s.put('orders',o.id,o));return o}
const remote=(o)=>({...shipping.payload(o,88),orderId:100+n});
before(async()=>{await transaction(s=>s.put('integrations','shipstation',{fingerprint:shipping.fingerprint(),enabled:true,store_id:88,stores:[{id:88,name:'Manual'}]}))});after(()=>{global.fetch=originalFetch;fs.rmSync(dir,{recursive:true,force:true})});
test('credentials stay server-side and connection excludes WooCommerce stores',async()=>{global.fetch=async(url,opts)=>{assert.equal(opts.headers.Authorization,'Basic '+Buffer.from('fixture-key:fixture-secret').toString('base64'));return{ok:true,json:async()=>[{storeId:88,storeName:'Manual',marketplaceId:0,active:true},{storeId:99,storeName:'Old Woo',marketplaceId:36,active:true}]}};const r=await shipping.check();assert.deepEqual(r.stores,[{id:88,name:'Manual'}]);assert.equal(JSON.stringify(shipping.status(r)).includes('fixture-secret'),false)});
test('test, draft and receipt-only orders never reach ShipStation',async()=>{let calls=0;global.fetch=async()=>{calls++;throw Error('unexpected')};for(const extra of [{is_test:true},{status:'awaiting_payment'},{status:'payment_submitted'},{receipt:null}])assert.equal((await shipping.send((await fixture(extra)).id)).status,'blocked');assert.equal(calls,0)});
test('paid export preserves cents with negative discount line, uses stable key and does not buy postage',async()=>{const o=await fixture();let posts=0,payload;global.fetch=async(url,opts)=>{if(opts.method==='GET')return{ok:true,json:async()=>({orders:[],pages:0})};assert.equal(url,'https://ssapi.shipstation.com/orders/createorder');posts++;payload=JSON.parse(opts.body);await new Promise(r=>setTimeout(r,5));return{ok:true,json:async()=>remote(o)}};const r=await Promise.all([shipping.send(o.id),shipping.send(o.id)]);assert.ok(r.some(x=>x.status==='synced'));assert.equal(posts,1);assert.equal(payload.items[1].unitPrice,-3.39);assert.equal(payload.items.reduce((n,i)=>n+i.quantity*i.unitPrice,0)+payload.shippingAmount+payload.taxAmount,payload.amountPaid);assert.equal(payload.orderKey,'glow-store-next-'+o.id);assert.equal(payload.weight,undefined);await shipping.send(o.id);assert.equal(posts,1)});
test('uncertain create is reconciled without a duplicate and conflicting remote orders are blocked',async()=>{const o=await fixture();let posts=0,visible=false;global.fetch=async(url,opts)=>{if(opts.method==='POST'){posts++;throw Error('timeout with private customer data')};return{ok:true,json:async()=>({orders:visible?[remote(o)]:[],pages:1})}};assert.equal((await shipping.send(o.id)).status,'needs_review');assert.equal((await shipping.send(o.id)).status,'needs_review');assert.equal(posts,1);visible=true;assert.equal((await shipping.send(o.id)).status,'synced');assert.equal(posts,1);const conflict=await fixture();global.fetch=async()=>({ok:true,json:async()=>({orders:[{...remote(conflict),amountPaid:1}],pages:1})});assert.equal((await shipping.send(conflict.id)).status,'failed')});
test('credential changes block ambiguous sends and definite rejection can retry',async()=>{const o=await fixture();let reject=true;global.fetch=async(url,opts)=>opts.method==='POST'?(reject?{ok:false,status:401}:{ok:true,json:async()=>remote(o)}):{ok:true,json:async()=>({orders:[],pages:0})};assert.equal((await shipping.send(o.id)).status,'failed');reject=false;assert.equal((await shipping.send(o.id)).status,'synced');const ambiguous=await fixture();global.fetch=async(url,opts)=>{if(opts.method==='POST')throw Error('timeout');return{ok:true,json:async()=>({orders:[],pages:0})}};await shipping.send(ambiguous.id);process.env.SHIPSTATION_API_SECRET='changed-secret';assert.equal((await shipping.send(ambiguous.id)).status,'not_connected');process.env.SHIPSTATION_API_SECRET='fixture-secret'});
test('tracking ignores returns and voided labels; valid outbound tracking marks shipped exactly once',async()=>{const o=await fixture({shipstation_order_id:555});await transaction(s=>s.put('outbox','shipstation-'+o.id,{account_fingerprint:shipping.fingerprint(),status:'synced'}));let valid=false;global.fetch=async(url)=>({ok:true,json:async()=>url.includes('/orders/')?{...remote(o),orderId:555,orderStatus:'shipped'}:{pages:1,shipments:[{orderId:555,voided:true,isReturnLabel:false,trackingNumber:'VOID'},{orderId:555,voided:false,isReturnLabel:true,trackingNumber:'RETURN'},...(valid?[{orderId:555,voided:false,isReturnLabel:false,trackingNumber:'TRACK123',shipmentId:123}]:[])]}});assert.equal((await shipping.tracking(o.id)).status,'needs_review');assert.equal((await transaction(s=>s.get('orders',o.id))).status,'paid');valid=true;assert.equal((await shipping.tracking(o.id)).status,'shipped');assert.equal((await transaction(s=>s.get('orders',o.id))).tracking,'TRACK123');assert.equal((await shipping.tracking(o.id)).status,'blocked')});
